### ISSUE TITLE
troublesome program

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#12]
only when pipelined. Works fine without
this program does not pause properly, and after resuming the program does not close. The stop button does not work. It does something strage to the clock and or CPU...

```
.text; main:
li $v0 10 # @{ pause() }@
syscall
```

**Comment by mbway** [comment]
seems to have been fixed in the process of fixing another issue

**Comment by mbway** [comment]
might have been a bit premature. Different issues now, namely
- after pausing and resuming, the play/step/stop buttons stay in the running & not paused state
- running again fails in a strange way (no exceptions)

**Comment by mbway** [comment]
the issue seems to be caused by the annotation being fired twice, because the pause() function that is called sets the CPU state to running=true paused=true, the annotation happens after the syscall which sets running=false so the pause() annotation brings the simulation back to life after it has ended.

More generally the problem is that if an annotation is attached to the instruction before the final syscall then it is run twice. If an annotation is placed on the last exit syscall, then the annotation is never fired because the simulation finishes before it can be (this is correct behaviour)

**Comment by mbway** [comment]
this issue can be closed now @charlie1329 right?

**Comment by charlie1329** [comment]
Yep I believe so :)
