### ISSUE TITLE
clearer item descriptions in the settings window

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#2]
If I didn't know they were there already: I would not be able to find the descriptions for the settings items by hovering over them. For some items, like the theme, the description is important because it lists the possible values. Maybe some layout where descriptions are always visible would be better?

**Comment by MichaelOultram** [comment]
I've been working on this enhancement and would like some feedback. Below is a screenshot of the options window in it's current state. There are still a few more non-aesthetic things I would like to do (like checking all the options actually do something) before merging into develop.

![options-overhaul](https://cloud.githubusercontent.com/assets/9907700/18809833/9b842c8e-827e-11e6-8213-6cad5d13eab1.png)

**Comment by mbway** [comment]
Holy Crap! that looks gorgeous!

That's a massive improvement I think. I would say the tick boxes are a little large, and I think you are using that microsoft UI font (segoe ui?) which we won't be able to ship with (but Windows users will have installed already)
