### ISSUE TITLE
editor cannot stop simulizer closing

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#20]
To reproduce
1. open a file
2. make an edit and don't save
3. exit simulizer. When prompted to save: click cancel

Result:
Simulizer closes anyway

The editor needs a way to signal the whole application needs to stay open. Cancel does work when closing only the editor window, but not Simulizer as a whole

**Comment by MichaelOultram** [comment]
Bug was caused by this [line](https://github.com/Simulizer/Simulizer/blob/e0eb48f842276bb6c515c7fe860d811ad905b3a8/src/main/java/simulizer/GuiMode.java#L92).
