### ISSUE TITLE
Search through help windows

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#22]
Add a search bar to the instruction and syscall windows to quickly search for the instruction or syscall that you want.

Ideally keep all the instructions in view but scroll to the best match and highlight all the matches. Search through both the instruction names and the descriptions.

As for a searching algorithm. I don't think regex is necessary. Case insensitive would be good and more emphasis on instruction names before descriptions (eg searching `b` should scroll to the `b` instruction, not the first instruction with a 'b' character in the description)

**Comment by MichaelOultram** [comment]
Functionality has been added in 4f7b4b8. Beautification has not.
