### ISSUE TITLE
current file appears not to be modified after restart

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#27]
to reproduce:
1. open a file
2. make a change
3. File > Options
4. close options and choose to restart
5. the change you made will remain but the editor will show not modified

**Comment by MichaelOultram** [comment]
Restarting the application is a tad hacky. It calls `app.start(primaryStage);` so all of the startup procedures run again. However it will not reset anything that is static (which you tend to like to use). I was considering removing the restart feature and instead have a popup saying restart to apply changes.

**Comment by MichaelOultram** [comment]
Issue is obsolete since the application no longer restarts itself
