### ISSUE TITLE
register window needs to show HI and LO

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#31]

**Comment by MichaelOultram** [comment]
Registers Window is using `simulizer.assembler.representation.Register` enum to display registers. Could HI and LO be put in there or do I need to add a special case?

**Comment by mbway** [comment]
I told Charlie not to add HI and LO to the enum because the enum is for general purpose registers only. So the register window will need special cases. I think Charlie added a new message which is sent when HI or LO is modified
