### ISSUE TITLE
mult instruction and associated machinery

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#4]
GCC uses the pair of instructions: `mult $a $b` followed by `mflo $c` to multiply `$a` and `$b` and store the lower word of the result in `$c`. This can also be achieved by `mul $c $a $b` however this is quite hard to automatically fix using `awk` or `sed`

the `mult` and `multi` instructions store the results in two special purpose registers `lo` and `hi` which can only be accessed through the `mflo` and `mfhi` instructions. All of these instructions must be implemented.

I don't think that `lo` and `hi` should be added to the `Register` enum because they are _not_ general purpose and cannot be used with any other instructions. I propose that they are stored as words in the CPU object and any messages to notify listeners of reads and writes to registers should have a new message to specify that `lo` and `hi` have changed (they will always change together) and in this case the register ID can be `null`. For example: `cpu.sendMessage(new RegisterChangedMessage.HiLoChangeMessage());` and have `HiLoChangeMessage extends RegisterChangedMessage` which sets the `registerChanged` field to `null`.

the CPU class should have getters for each of the special purpose registers eg `getHiReg()`

The simulation bridge should have `getHiReg()` and `getLoReg()` but I don't think `hi` and `lo` objects should be added to the API to allow use like the other registers (ie `$s0.get()`) because again, they are not general purpose and should be treated differently.

**Comment by charlie1329** [comment]
I think I should be able to sort that out (in the CPU anyway)

**Comment by charlie1329** [comment]
After my last commit, I have added some tests for the function of these registers etc. and all seems well so I think I can consider this closed :)
