### ISSUE TITLE
Editor Ctrl+plus and Ctrl+minus doesn't work when popped out

### ISSUE THREAD

**Issue by mbway** [Simulizer/Simulizer#40]
it appears that Ctrl+C and Ctrl+V still work so this is strange

**Comment by MichaelOultram** [comment]
If you have tried to attach a listener to the InternalWindow (and not a component on the InternalWindow) then you'll need to update it to use `getEventManager()` so that the events can be transferred to the popped out window.

**Comment by mbway** [comment]
perfect, thanks :) very strange how Ctrl+C and Ctrl+V still appear to work without the fix...
