### ISSUE TITLE
GUI mode doesn't listen for mac save key shortcut

### ISSUE THREAD

**Issue by SamTebbs33** [Simulizer/Simulizer#51]
The GUI mode doesn't currently listen for the mac save shortcut Cmd-S but does listen for the windows version Ctrl-S.

I'd be willing to implement this via a PR with some guidance regarding which file this would be best added to.

**Comment by mbway** [comment]
sorry but this was already fixed in ed0b7c1a8d5cc1ba747839d3043b69b773570585 (which is included in the new release) by another student. If you find any more problems let us know :)
