### ISSUE TITLE
lo and hi registers are not updated on a div instruction

### ISSUE THREAD

**Issue by MichaelOultram** [Simulizer/Simulizer#53]
lo and hi registers are updated for the mul instructions but not the div instructions.
Housemate who found this bug was not happy.

**Comment by charlie1329** [comment]
The div and divu instructions now combine a sort of pseudo instruction version where div takes a destination register, and the true version where it is stored in lo and hi. This is by no means an ideal solution yet it will suffice temporarily as changing the instruction set while an assignment in progress would be highly inappropriate. This issue can now be closed I believe
